User.create(email:"skittles@skittles.com", username:"Skittles", password:"iluvskittles")
User.create(email:"sally@flatiron.com", username:"Sally", password:"itssalley123")
User.create(email:"ish@flatiron.com", username:"Ish", password:"itsish123")
User.create(email:"rona@flatiron.com", username:"Rona", password:"itsrona123")
User.create(email:"chindalath@flatiron.com", username:"Chindalath", password:"itschindalath123")

Task.create(task_descr:"Water plants", user_id:1)
Task.create(task_descr:"Take out garbage", user_id:1)
Task.create(task_descr:"Laundry", user_id:1)
Task.create(task_descr:"Walk the dog", user_id:2)
Task.create(task_descr:"Water plants", user_id:3)
Task.create(task_descr:"Laundry", user_id:3)
Task.create(task_descr:"Walk the dog", user_id:4)
Task.create(task_descr:"Mop the floors", user_id:4)
Task.create(task_descr:"Water plants", user_id:4)
Task.create(task_descr:"Walk the dog", user_id:5)
Task.create(task_descr:"Take out garbage", user_id:5)